### ISSUE TITLE
Build out more game verbs

### ISSUE THREAD

**Issue by wrobe0709** [wrobe0709/Aquarius#32]
**Your game must support an action vocabulary space (verbs) of at least ten primary actions (hit, pull, go, eat, etc.). These verbs must allow interaction with each feature in each room (a generic "you can't eat that" type of message is OK to use with some verbs).**

- Right now you can "use" any feature but we need to make it so you can "read black tome" or "smash barrel 1". Stuff like that.

**Some verbs must cause the player to move between rooms.**

- we already have this implemented like the "passageway" and "staircase" features will move you.

**Comment by jeanBEY** [comment]
since "examine" was a listed verb I added it ("branch:  building out verbs - examine & quit", merged 8.5.17)

**Comment by wrobe0709** [comment]
I think "stand on" could be a verb we use in the diamond room with the chair. We could also use "flip" for the switch in the diamond room.
