### ISSUE TITLE
Exits in short and long form

### ISSUE THREAD

**Issue by wrobe0709** [wrobe0709/Aquarius#51]
**Exits from a room must be described in both the short-form and long-form descriptions, and should include a direction. For example: "There is a dank-smelling staircase, descending into the dark, at the end of the hall on the north wall", or "I can see clouds to the east and west that I think I can jump to from here".**

- We almost have this all setup only need to actually say the room name that corresponds to the direction

**Comment by jeanBEY** [comment]
Added room names to the short/long exit descriptions in JSON files--so player knows they can either type, "go north" or "Gear Room" for example.
