### ISSUE TITLE
Clean up printing

### ISSUE THREAD

**Issue by wrobe0709** [wrobe0709/Aquarius#58]
I think it would be good if went through and made sure everything printed out nicely. In some places we use tab indents in others we don't. Being consistent will make the project look better.

**Comment by wrobe0709** [comment]
I have done some work on this but there are a few areas that we can clean up still.

**Comment by jeanBEY** [comment]
Removed newlines from JSON files, long/short descriptions.  https://github.com/wrobe0709/Aquarius/pull/67

**Comment by wrobe0709** [comment]
I think this is good so I'll close it.
